# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'images' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for images
  pod 'Kingfisher', '~> 4.0'
  pod 'BadgeSwift', '~> 6.0'

  target 'imagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
